< a href='https://home.howard.edu/ '> <img src='hu_logo.png'/></a>

In [1]:
import numpy as np
import pandas as pd

In [6]:
array_1 = np.array([1,2,3,4])

In [7]:
array_2 = np.array([4,3,2,1])

In [5]:
len(array_1)

4

In [10]:
for i in range(len(array_1)):
    dot = array_1[i]*array_2.sum()
    dot

In [11]:
dot

40

In [12]:
array_1 @ array_2

20

In [13]:
array_1.dot(array_2)

20

In [14]:
array_3 = np.sqrt(array_1)

In [15]:
array_3

array([1.        , 1.41421356, 1.73205081, 2.        ])

In [16]:
another_arr = np.array([1,2,3,4,5,6,7,8,9,10])

In [17]:
another_arr[0:5]

array([1, 2, 3, 4, 5])

# Broadcasting

In [19]:
another_arr[0:5] = 100

In [20]:
another_arr

array([100, 100, 100, 100, 100,   6,   7,   8,   9,  10])

In [21]:
another_arr[:] = 1

In [22]:
another_arr

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [29]:
three_by_three = np.array(([1,2,3],[4,5,6],[7,8,9]))

In [30]:
three_by_three

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [25]:
# three_by_three[:] = 0

In [26]:
three_by_three

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

### I want to grab the first column in three_by_three

In [31]:
three_by_three[:][0]

array([1, 2, 3])

In [32]:
# Slicing _ HW due this Monday

In [34]:
three_by_three > 4

array([[False, False, False],
       [False,  True,  True],
       [ True,  True,  True]])

In [35]:
new_matrix = three_by_three > 4

In [36]:
new_matrix

array([[False, False, False],
       [False,  True,  True],
       [ True,  True,  True]])

In [37]:
# Split Method

In [38]:
# Given a string s ='a b c d', I want to find a list in the form  ['a','b','c','d']

In [42]:
s = 'a b c d'
a_list = []
for char in s:
    if char == ' ':
        continue
    else:
        a_list.append(char)
    a_list

In [43]:
a_list

['a', 'b', 'c', 'd']

In [44]:
s.split()

['a', 'b', 'c', 'd']

In [45]:
from numpy.random import randn

In [46]:
df = pd.DataFrame(randn(5,4),index = 'A B C D E'.split(), columns ='W X Y Z'.split())

In [47]:
df

W         X         Y         Z
A  1.617980 -1.793674  0.911299  0.650781
B  0.895807  0.556888  0.990584  0.204583
C  0.934240 -1.404877  0.156542  0.677424
D -0.585287 -0.123403 -1.070218  0.353383
E  0.047721 -1.015203 -1.870198 -0.699452

In [48]:
df['W']

A    1.617980
B    0.895807
C    0.934240
D   -0.585287
E    0.047721
Name: W, dtype: float64

In [52]:
# I want to grab the first two columns
df[['W','X']]

W         X
A  1.617980 -1.793674
B  0.895807  0.556888
C  0.934240 -1.404877
D -0.585287 -0.123403
E  0.047721 -1.015203

In [53]:
df.W

A    1.617980
B    0.895807
C    0.934240
D   -0.585287
E    0.047721
Name: W, dtype: float64

In [54]:
type(df.W)

pandas.core.series.Series

In [55]:
df['New'] = df['W'] + df['Y']

In [56]:
df

W         X         Y         Z       New
A  1.617980 -1.793674  0.911299  0.650781  2.529279
B  0.895807  0.556888  0.990584  0.204583  1.886390
C  0.934240 -1.404877  0.156542  0.677424  1.090783
D -0.585287 -0.123403 -1.070218  0.353383 -1.655505
E  0.047721 -1.015203 -1.870198 -0.699452 -1.822477

In [57]:
df.drop('New', axis = 1)

W         X         Y         Z
A  1.617980 -1.793674  0.911299  0.650781
B  0.895807  0.556888  0.990584  0.204583
C  0.934240 -1.404877  0.156542  0.677424
D -0.585287 -0.123403 -1.070218  0.353383
E  0.047721 -1.015203 -1.870198 -0.699452

In [58]:
df

W         X         Y         Z       New
A  1.617980 -1.793674  0.911299  0.650781  2.529279
B  0.895807  0.556888  0.990584  0.204583  1.886390
C  0.934240 -1.404877  0.156542  0.677424  1.090783
D -0.585287 -0.123403 -1.070218  0.353383 -1.655505
E  0.047721 -1.015203 -1.870198 -0.699452 -1.822477

In [59]:
df.drop('New', axis = 1, inplace = True)

In [60]:
df

W         X         Y         Z
A  1.617980 -1.793674  0.911299  0.650781
B  0.895807  0.556888  0.990584  0.204583
C  0.934240 -1.404877  0.156542  0.677424
D -0.585287 -0.123403 -1.070218  0.353383
E  0.047721 -1.015203 -1.870198 -0.699452